# Generated by Django 5.0.8 on 2024-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_plugin_buildingplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
